### ISSUE TITLE
updateApprovalState Updating All Rows in the Approval Table

### ISSUE THREAD

**Issue by moedayraki** [cjmellor/approval#22]
When using Approval::find(3)->approve(). It's updating 1,2,3.

**Comment by cjmellor** [comment]
Hi,

Thanks for bringing this to my attention. I will look into it.

**Comment by cjmellor** [comment]
I've fixed the issues and will add a PR and release soon.

**Comment by cjmellor** [comment]
Issue fixed with release: v1.1.3
