### ISSUE TITLE
Bug: ```Approval::reject()``` rejects all pending approvals instead of one specific approval

### ISSUE THREAD

**Issue by lewis-munyi** [cjmellor/approval#24]
As said in the title `$approval->reject()` when called proceeds to reject all pending models instead of just the one queried

Sample code:
```
$approvals = Approval::pending()->get();

count($approvals); // 10

$approval->first()->reject();

Approval::pending()->count(); // 0

**Comment by cjmellor** [comment]
Thanks for bringing this to my attention @lewis-munyi 

I clearly overlooked this when I did #23 but all good now.
