### ISSUE TITLE
Problem with ide-helper generator

### ISSUE THREAD

**Issue by Temepest74** [cjmellor/approval#35]
I am talking about this https://github.com/barryvdh/laravel-ide-helper. A must use package if you develop with vscode. 
If you run 
```
php artisan ide-helper:generate -q
```
You will get
```
Exception: Target class [approval] does not exist.
Skipping \Cjmellor\Approval\Facades\Approval.
Exception: Target class [approval] does not exist.
Skipping \Cjmellor\Approval\Facades\Approval.
```

**Comment by cjmellor** [comment]
Hi,

I don't use this package so I can't give any advice.

I'm open to any PR's though from those who do use it and fix it.

Thanks.

**Comment by Temepest74** [comment]
Hmm, if i have time, I may look into this
