### ISSUE TITLE
Approval fails for models with a morphMap

### ISSUE THREAD

**Issue by AndrewMast** [cjmellor/approval#38]
When a model has a morphMap alias ([see docs](https://laravel.com/docs/10.x/eloquent-relationships#custom-polymorphic-types)), approving the Approval results in the error `Error: Class "model_name" not found.`

When creating the class, `Relation::getMorphedModel($approvalable_type)` should be called instead of [directly instancing](https://github.com/cjmellor/approval/blob/9ba8674ea02d5ceee50fb53c8b7b55fb977d6404/src/Scopes/ApprovalStateScope.php#L99C13-L99C14) the database table value.

**Comment by cjmellor** [comment]
Thanks for bringing this to my attention. 

I'll take a look at it later but also open to a PR to help out.

**Comment by cjmellor** [comment]
Thanks again for the heads up!
