### ISSUE TITLE
Issue when rolling back models that contain json fields

### ISSUE THREAD

**Issue by MennoM** [cjmellor/approval#54]
This is done in Laravel 10

Let's say I've got the following Model:
```
class Post extends Model
{
use MustBeApproved;

protected $fillable = [
    "config",
];

protected $casts = [
    "config" => "json",
];
}
```

Now let's assume we're making different API calls where we change this Model and approve the modifications, the creation works fine
```
$post = new Post();
$post->config = ['checked' => false];
$post->save();
```

When updating the post (which needs an approval)
```
$post = Post::find([id]);
$post->config = ['checked' => true];
$post->save();
```

I get the following approvals, which I already approved in this image, but you can already see the discrepancy in data
![post_approved](https://github.com/cjmellor/approval/assets/3264201/2f8fe7fc-09c8-465e-bc1f-c26853c92486)

after rolling back this change I get the following approvals
![post_rolled_back](https://github.com/cjmellor/approval/assets/3264201/2edaa2f1-3622-4239-b243-f8ac3584a069)

Now after approving the rolled-back approval (which is pending as well) I get the error
`"message": "json_decode(): Argument https://github.com/cjmellor/approval/pull/1 ($json) must be of type string, array given", "exception": "TypeError", "file": "/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Casts/Json.php"`

**Comment by cjmellor** [comment]
@MennoM I did a PR (#55) for this. Tests are passing, but be good to get clarity on if it fixes your own issue. Are you able to pull down the PR and test it?

Thanks

**Comment by MennoM** [comment]
Your change for the updating and rolling back of json data looks right, but I think I have another issue resulting from the 1.4.4 release.
When change data I get the following approval, notice the user_id in new_data:
<img width="1078" alt="array_data" src="https://github.com/cjmellor/approval/assets/3264201/7a187042-783e-4be4-8468-7d384d8a9969">

When approving this I get the following error:
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user_id' in 'field list'`

**Comment by cjmellor** [comment]
Hmm, I may have overlooked something here... ugh. 

Just go back the previous version for now.

I assume the Model you're approving doesn't have a `user_id` foreign key?

**Comment by cjmellor** [comment]
Yeah... in hindsight, I dunno why I added that -- wasn't thinking straight 😅 

I guess, try again? 😂

**Comment by MennoM** [comment]
Thanks for the update, all seems well now!
I'll keep working with this and will let you know if anything out of the ordinary will catch my attention
