### ISSUE TITLE
approvalModelExists() MySQL bug

### ISSUE THREAD

**Issue by rawilk** [cjmellor/approval#6]
In your `approvalModelExists` method, you are checking for an exact match for `new_data` and `original_data` via `json_encode`. I'm not sure how .sqlite formats data in json columns, but it appears to be the same as `json_encode`, since it works for your tests. In my local database I'm running MySQL 8, and it puts spaces between the key and value pairs in those columns, so the exact match in your query isn't working because of slight formatting differences between php and mysql, and thus duplicates will always be created.

I've tried the following and it seems to work:

```php
return Approval::where('state', ApprovalStatus::Pending)
    ->whereJsonContains('new_data', $model->getDirty())
    ->whereJsonContains('original_data', $model->getOriginalMatchingChanges())
    ->exists();
```

If you want, I can submit a PR using the `whereJsonContains` query builder method.

**Comment by cjmellor** [comment]
Hey,

Yeah I'm open to a PR being submitted if you think it would help. 

Can you add a quick scenario with code examples of what's broke and how you're looking to resolve it?

Thanks!

**Comment by rawilk** [comment]
It's basically any time I go to create a new model or update an existing one. I always get duplicates because of how mysql formats the json, which causes the exists() check to always return false.

In these examples, I have a Student model, which can have many StudentEnrollment models. When I go to insert or update one, I am going to require an approval before a new enrollment can be inserted or updated.

Create example:

```php
$student->enrollments()->create([
    'enroll_start' => '2022-01-01',
]);

$student->enrollments()->create([
    'enroll_start' => '2022-01-01',
]);
```

This results in two approvals being inserted for the same exact data. When I dump the `json_encode($model->getDirty())`, I get this: `{"assignee_id":123456,"enroll_start":"2022-01-01 00:00:00"}`. In my screenshot below, you can see the database formats the data differently, and I think that is causing the issue with the query returning a match here.

![image](https://user-images.githubusercontent.com/22842525/182179551-7f680fd2-db58-430e-ab99-afedca7acf68.png)

Updating data is basically the same result.

**Comment by cjmellor** [comment]
Ah I see. I think it's a case of not originally considering this kind of scenario -- very hard to predict lots of different scenarios, especially when my original idea for this package was to use it for a project I'm planning. 

This is the joys of open source though, where other people can spot these things and hopefully help out with PR's or advice. 

As I say, you're welcome to PR anything you wish if you feel you have a working solution for an issue and I will look at it 😊

**Comment by rawilk** [comment]
> This is the joys of open source though, where other people can spot these things and hopefully help out with PR's or advice.

That's part of the reason why I open source some of my own packages is sometimes other developers can help spot/fix issues you didn't even notice or think of 😄
