### ISSUE TITLE
Class "Spatie\LaravelPackageTools\PackageServiceProvider" not found  

### ISSUE THREAD

**Issue by anchovie91471** [cjmellor/approval#66]
I installed this package in Laravel 10.48.20/PHP 8.2.22 and got the following error:
 
`Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In ApprovalServiceProvider.php line 8:
                                                                       
  Class "Spatie\LaravelPackageTools\PackageServiceProvider" not found  
                                                                       

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
`
Any idea why this would happen?

**Comment by anchovie91471** [comment]
OK. Thank you!

**Comment by anchovie91471** [comment]
That worked! Thank you again!

**Comment by To-heeb** [comment]
I still have the same issue, I have done the above and it is still the same

**Comment by mojowill** [comment]
I'm seeing the same issue on a fresh install on a pretty fresh Laravel install.

**Comment by cjmellor** [comment]
Hmm, I'll see if I can replicate and if so, sort something out.

**Comment by mojowill** [comment]
I was able to work around by explicitly requiring Spaties package tools as a requirement (not dev)

**Comment by mojowill** [comment]
> Interesting. Will still take a look. Ideally I want to take out all the Spatie stuff, it just causes problems

According to their Package Skeleton package tools should be in the main require not require-dev.

https://github.com/spatie/package-skeleton-laravel/blob/main/composer.json

**Comment by cjmellor** [comment]
Thanks for the guidance! I'll change it tomorrow, or if anyone wants to do a PR 😜

**Comment by mojowill** [comment]
PR raised

**Comment by To-heeb** [comment]
Thanks @mojowill and @cjmellor, I will now  be able to use it with no issue, will keep an eye on the PR when it is merged.

> PR raised

**Comment by cjmellor** [comment]
Fixed via #72
